name: Setup
description: Sets up pnpm, Node and installs dependencies
runs:
  using: composite
  steps:
    - name: Setup pnpm and Node
      uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c # v2.0.0
      with:
        runtime: node@24
        cache: true
